
name: Build Goldleaf

on: [push]
jobs:
  Goldleaf:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm
    steps:
    - uses: actions/checkout@v1
    - name: Update repo
      run: |
        git submodule update --init --recursive
        
    - name: Build Goldleaf
      run: |
        make initial -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: Goldleaf
        path: Goldleaf/Goldleaf.nro
